import { Archivo } from "next/font/google";
import "./styles/_globals.scss";
import Header from "./components/Header";

const archivo = Archivo({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={archivo.className}>
        <Header/>
        {children}
      </body>
    </html>
  );
}
